name: Post-Deployment ETL Execution - Preview Branch

on:
  workflow_dispatch:

jobs:
  run-etl-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.10.12
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12'
          
      - name: Install dependencies
        run: |
          pip install -r Data/ETL/Scripts/requirements.txt
          
      - name: Run ETL Script 1
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          SCRAPEPEDDATA_DB: ${{ secrets.SCRAPEPEDDATA_DB }}
        run: python Data/ETL/Scripts/ETL_Extract_and_Load_Raw_WS_LinkedIn_JobData.py

      - name: Run ETL Script 2
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          SCRAPEPEDDATA_DB: ${{ secrets.SCRAPEPEDDATA_DB }}
          CLIENTDATA_DB: ${{ secrets.CLIENTDATA_DB }}
          CLIENTDATA_COMPANY_COL: ${{ secrets.CLIENTDATA_COMPANY_COL }}
        run: python Data/ETL/Scripts/ETL_Extract_and_Load_Raw_WS_LinkedIn_JobData.py
